name: Linting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
  pylint:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Analysing the code with pylint
      run: |
        python -m pip install --upgrade pip
        pip install .[lint]
        pylint $(git ls-files '*.py')
  flake8:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Analysing the code with flake8
      run: |
        python -m pip install --upgrade pip
        pip install .[lint]
        flake8
  bandit:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Analysing the code with bandit
      run: |
        python -m pip install --upgrade pip
        pip install .[lint]
        bandit -c pyproject.toml -r .
